name: CI
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: |
          mkdir storage
          echo "${{ secrets.FIREBASE_KEY }}" | base64 -d > storage/serviceAccount.json
          echo "FIREBASE_URL=${{ secrets.FIREBASE_URL }}" > .env
      - name: deploy and delete previous version in Google App Engine
        uses: vijayp23/deploy-gae-action@1.0.1
        with:
          service-account: ${{ secrets.GCP_SA_KEY }}
          project-id: ${{ secrets.PROJECT_ID }}
          config-files: './app.yaml'
          delete-previous-versions: true
