name: CI
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: |
          mkdir storage
          echo "${{ secrets.FIREBASE_KEY }}" | base64 -d > storage/serviceAccount.json
          echo "FIREBASE_URL=${{ secrets.FIREBASE_URL }}" > .env
      - id: deploy
        uses: google-github-actions/deploy-appengine@main
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          credentials: ${{ secrets.GCP_SA_KEY }}
      - id: test
        run: curl "${{ steps.deploy.outputs.url }}/health"
